const builds = [
    {
      id: 1,
      nomeBuid: "PC Gamer Top de Linha",
      processador: "Intel Core i9-14900K",
      placaVideo: "NVIDIA GeForce RTX 4090",
      ram: "64GB DDR5",
      armazenamento: "2TB NVMe Gen4 SSD",
      preco: 18500,
      categoria: "Gamer Extremo",
      desempenho: "Absoluto",
      ValorProcessador: 250,
      valorPlacaVideo: 250,
      valorTotalRam:9000,
      valorTotalArmazenamento:9000
    },
    {
      id: 2,
      nomeBuid: "Estação de Trabalho Criativa",
      processador: "AMD Ryzen 9 7900X",
      placaVideo: "NVIDIA GeForce RTX 4070 Ti",
      ram: "64GB DDR5",
      armazenamento: "2TB NVMe SSD + 8TB HDD",
      preco: 13200,
      categoria: "Produtividade/Edição",
      desempenho: "Profissional",
      ValorProcessador: 6500,
      valorPlacaVideo: 6500,
      valorTotalRam:100,
      valorTotalArmazenamento:100
    },
    {
      id: 3,
      nomeBuid: "PC Gamer de Entrada",
      processador: "AMD Ryzen 5 7600",
      placaVideo: "AMD Radeon RX 7600",
      ram: "16GB DDR5",
      armazenamento: "1TB NVMe SSD",
      preco: 4800,
      categoria: "Gamer Básico",
      desempenho: "Bom",
      ValorProcessador: 2000,
      valorPlacaVideo: 2000,
      valorTotalRam:400,
      valorTotalArmazenamento:400
    },
    {
      id: 4,
      nomeBuid: "Máquina de Design Gráfico",
      processador: "Intel Core i7-13700",
      placaVideo: "NVIDIA GeForce RTX 4060",
      ram: "32GB DDR4",
      armazenamento: "1TB NVMe SSD",
      preco: 8900,
      categoria: "Design",
      desempenho: "Alto",
      ValorProcessador: 4000,
      valorPlacaVideo: 4000,
      valorTotalRam: 450,
      valorTotalArmazenamento: 450
    },
    {
      id: 5,
      nomeBuid: "PC Compacto Essencial",
      processador: "Intel Core i5-12400",
      placaVideo: "Integrada (Intel UHD Graphics)",
      ram: "16GB DDR4",
      armazenamento: "512GB NVMe SSD",
      preco: 3200,
      categoria: "Home Office/Estudo",
      desempenho: "Básico",
      ValorProcessador: 1000 ,
      valorPlacaVideo: 1000,
      valorTotalRam: 600,
      valorTotalArmazenamento: 600
    },
    {
      id: 6,
      nomeBuid: "PC Gamer Intermediário",
      processador: "AMD Ryzen 7 7700X",
      placaVideo: "NVIDIA GeForce RTX 4070 Super",
      ram: "32GB DDR5",
      armazenamento: "2TB NVMe SSD",
      preco: 10500,
      categoria: "Gamer",
      desempenho: "Muito Alto",
      ValorProcessador: 5000,
      valorPlacaVideo: 5000,
      valorTotalRam: 250,
      valorTotalArmazenamento: 250
    },
    {
      id: 7,
      nomeBuid: "Computador de Escritório",
      processador: "AMD Ryzen 5 5600G",
      placaVideo: "Integrada (Radeon Graphics)",
      ram: "8GB DDR4",
      armazenamento: "256GB SSD",
      preco: 2400,
      categoria: "Escritório",
      desempenho: "Básico",
      ValorProcessador: 1000,
      valorPlacaVideo: 1000,
      valorTotalRam: 200,
      valorTotalArmazenamento: 200
    },
    {
      id: 8,
      nomeBuid: "PC para Estudantes e Multimídia",
      processador: "Intel Core i5-13400F",
      placaVideo: "NVIDIA GeForce GTX 1660 Super",
      ram: "16GB DDR4",
      armazenamento: "1TB NVMe SSD",
      preco: 4500,
      categoria: "Estudo/Lazer",
      desempenho: "Médio",
      ValorProcessador: 2000,
      valorPlacaVideo: 2000,
      valorTotalRam: 2000,
      valorTotalArmazenamento: 2000
    },
    {
      id: 9,
      nomeBuid: "Workstation de IA e Machine Learning",
      processador: "Intel Core i9-13900K",
      placaVideo: "NVIDIA GeForce RTX 4080",
      ram: "128GB DDR5",
      armazenamento: "4TB NVMe SSD",
      preco: 21000,
      categoria: "Profissional",
      desempenho: "Extremo",
      ValorProcessador: 10000,
      valorPlacaVideo:9000 ,
      valorTotalRam: 10000,
      valorTotalArmazenamento: 100000
    },
    {
      id: 10,
      nomeBuid: "PC Multiuso Econômico",
      processador: "Intel Core i5-13600K",
      placaVideo: "NVIDIA GeForce RTX 3060",
      ram: "16GB DDR4",
      armazenamento: "1TB NVMe SSD",
      preco: 6800,
      categoria: "Geral/Multimídia",
      desempenho: "Alto",
      ValorProcessador: 200,
      valorPlacaVideo: 2400,
      valorTotalRam:4000,
      valorTotalArmazenamento:200
    }
  ]

  export default {builds}